import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "./page";
import { Roboto } from 'next/font/google'
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        

        <SidebarProvider>{children}</SidebarProvider>
     
        
      </body>
    </html>
  );
}
